import type { Metadata } from "next";
import Link from "next/link";
import { guides } from "./levels";

export const metadata: Metadata = { title: { absolute: "Royal Smash Walkthroughs: Level 51–80 Solutions" }, description: "Stuck in Royal Smash? Find direct walkthroughs for levels 51 through 80, including hard and super hard physics puzzles.", alternates: { canonical: "/" } };

export default function Home() {
  return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">THE UNOFFICIAL WALKTHROUGH</p><h1>Every tower has a <em>weak point.</em></h1><p>Direct, step-by-step Royal Smash: Physics Puzzle solutions for the levels where the challenge starts to bite.</p><div className="actions"><Link className="button" href="/level/51">Start at Level 51</Link><Link className="text-link" href="/walkthrough">Browse all levels →</Link></div></div><div className="tower" aria-label="Decorative collapsing block tower"><i/><i/><i/><i/><i/><i/><span>SMASH</span></div></section><section className="quick"><div><b>30</b><span>LEVEL GUIDES</span></div><div><b>51–80</b><span>HARD LEVELS</span></div><div><b>3</b><span>STEPS PER SOLUTION</span></div></section><section className="section"><div className="section-title"><div><p className="eyebrow">CHOOSE YOUR LEVEL</p><h2>Royal Smash level solutions</h2></div><p>Jump directly to the puzzle blocking you. Every page keeps the answer first and links to the levels before and after it.</p></div><div className="level-grid">{guides.map(g => <Link href={`/level/${g.level}`} key={g.level} className={g.difficulty === "Super Hard" ? "featured" : ""}><small>{g.difficulty}</small><strong>{g.level}</strong><span>{g.mechanic} →</span></Link>)}</div></section><section className="how"><p className="eyebrow">HOW TO USE THESE GUIDES</p><h2>Observe. Aim. Let physics finish.</h2><div><article><b>01</b><h3>Match the layout</h3><p>Confirm you are on the correct level before making the first move.</p></article><article><b>02</b><h3>Make one move</h3><p>Follow each step in order. The first weak point determines the whole collapse.</p></article><article><b>03</b><h3>Wait for motion</h3><p>Let every block settle before the next input to avoid wasting a move.</p></article></div></section></main>;
}
